import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import SmoothScrolling from "./components/SmoothScrolling";
import { ViewTransitions } from "next-view-transitions";
import Footer from "./components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
// import localFont from "next/font/local";

// const myFont = localFont({
//   src: "/fonts/sec.woff2",
//   weight: "400",
//   display: "swap",
// });
import { DM_Sans } from "next/font/google";

const inter = DM_Sans({
  subsets: ["latin"],
  display: "swap", // ensures no flicker
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Sfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="main-clr overflow-x-hidden relative">
        <ViewTransitions>
          <SmoothScrolling>
            {/* Noise GIF Background */}
            <div
              className="fixed top-0 left-0 w-full h-full z-20 pointer-events-none overflow-hidden"
              style={{
                background: `url('/videos/5w5m.gif') center center no-repeat`,
                backgroundSize: "cover",
                opacity: 0.01,
              }}
            />

            {/* Ripple Effect just above the noise */}

            {/* Foreground UI */}
            <Navbar />
            <main>
              {children}
              <SpeedInsights />
            </main>
          </SmoothScrolling>
        </ViewTransitions>
      </body>
    </html>
  );
}
